/// Pozycje pol na blankiecie w pikselach (canvas 1000x1414 px).
/// GENERATED by tools/kalibrator.py
class FieldPositions {
  FieldPositions._();

  static const double pxToPt = 595.28 / 1000.0;

  static const double bottomOffsetPx = 521.9;

  static const double cellStep27Px = 24.0;
  static const double cellWidth27Px = 21.0;
  static const double cellStep26Px = 24.1;
  static const double cellWidth26Px = 22.0;

  static const double nazwaOdbiorcyXPx = 171.7;
  static const double nazwaOdbiorcyTop = 80.5;
  static const double nazwaOdbiorcyH = 34.0;
  static const double nazwaOdbiorcyCdTop = 114.5;
  static const double nazwaOdbiorcyCdH = 34.0;
  static const double nrRachunkuOdbiorcyXPx = 167.8;
  static const double nrRachunkuOdbiorcyTop = 158.4;
  static const double nrRachunkuOdbiorcyH = 40.0;
  static const double kwotaTop = 196.8;
  static const double kwotaH = 40.0;
  static const double rachunekZleceniodawcyXPx = 169.0;
  static const double rachunekZleceniodawcyTop = 236.4;
  static const double rachunekZleceniodawcyH = 40.0;
  static const double nadawcaNazwaXPx = 171.3;
  static const double nadawcaNazwaTop = 283.7;
  static const double nadawcaNazwaH = 34.0;
  static const double nadawcaAdresTop = 317.7;
  static const double nadawcaAdresH = 34.0;
  static const double tytulemXPx = 171.7;
  static const double tytulemTop = 368.3;
  static const double tytulemH = 34.0;
  static const double tytulemCdTop = 402.3;
  static const double tytulemCdH = 34.0;

  static const double walutaXPx = 435.0;
  static const double walutaStepPx = 24.0;
  static const double kwotaXPx = 534.2;
  static const double kwotaStepPx = 23.5;
  static const double kwotaCellWidthPx = 18.0;
}
